/**
 * Maestro-flow-first capture planning.
 *
 * Instead of deep-linking each screen, we group the screen graph into **chunks**
 * (auth, one per tab, root modals) and generate one editable **Maestro flow file
 * per chunk** that walks the UI and screenshots each screen. The generated flow
 * is a scaffold: launch + auth + a labelled block per screen with best-effort
 * navigation (tab taps we can infer) and a `takeScreenshot` whose filename
 * matches what the PDF renderer expects. You refine the hard transitions, run the
 * chunk, reconcile misses, and re-run.
 *
 * Chunking and the expected-screenshot list are deterministic functions of the
 * graph, so every tool recomputes them the same way — nothing extra to persist.
 */
import path from "node:path";
import { DocState, ScreenNode } from "../util/types.js";

/** The screenshot label for a (screen, state): "(tabs)__feed__index__default". */
export function screenshotLabel(nodeId: string, state: string): string {
  return `${nodeId.replace(/\//g, "__")}__${state}`;
}

/** Absolute PNG path for a (screen, state) under the captures dir (for existence checks). */
export function screenshotPath(capturesDir: string, nodeId: string, state: string): string {
  return path.join(capturesDir, `${screenshotLabel(nodeId, state)}.png`);
}

/** Screenshot path WITHOUT the .png extension — Maestro's `takeScreenshot` appends it. */
export function screenshotBase(capturesDir: string, nodeId: string, state: string): string {
  return path.join(capturesDir, screenshotLabel(nodeId, state));
}

/** The captures dir for a project (deterministic; mirrors session.ts). */
export function capturesDirFor(projectRoot: string): string {
  return path.join(projectRoot, ".docmcp", "captures");
}

/** The flows dir + a chunk's flow-file path. */
export function flowsDirFor(projectRoot: string): string {
  return path.join(projectRoot, ".docmcp", "flows");
}
export function chunkFlowFile(projectRoot: string, chunkId: string): string {
  return path.join(flowsDirFor(projectRoot), `${chunkId}.yaml`);
}

export interface Chunk {
  id: string;
  title: string;
  nodes: ScreenNode[];
}

/** Which chunk a screen belongs to: auth · one per tab · everything else (root). */
function chunkKey(id: string): string {
  if (id.startsWith("(auth)")) return "auth";
  const tab = id.match(/^\(tabs\)\/([^/]+)(?:\/|$)/);
  if (tab) return `tab-${tab[1]}`;
  return "root";
}

function humanize(s: string): string {
  return s.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()).trim();
}

function chunkTitle(id: string): string {
  if (id === "auth") return "Auth";
  if (id === "root") return "Root & Modals";
  return `${humanize(id.replace(/^tab-/, ""))} tab`;
}

/** Group the graph's screens into ordered chunks. */
export function chunkScreens(state: DocState): Chunk[] {
  const byKey = new Map<string, ScreenNode[]>();
  for (const node of state.screenGraph.nodes) {
    const k = chunkKey(node.id);
    (byKey.get(k) ?? byKey.set(k, []).get(k)!).push(node);
  }
  // Stable order: auth, tabs (alpha), root last.
  const order = (k: string) => (k === "auth" ? 0 : k === "root" ? 2 : 1);
  return [...byKey.entries()]
    .sort((a, b) => order(a[0]) - order(b[0]) || a[0].localeCompare(b[0]))
    .map(([id, nodes]) => ({ id, title: chunkTitle(id), nodes }));
}

/** Every (screen, state) a chunk's flow is expected to produce. */
export function chunkExpected(chunk: Chunk): { nodeId: string; state: string; label: string }[] {
  const out: { nodeId: string; state: string; label: string }[] = [];
  for (const n of chunk.nodes) {
    for (const st of n.states) out.push({ nodeId: n.id, state: st, label: screenshotLabel(n.id, st) });
  }
  return out;
}

/** Is this the index screen of a tab (so a tab-bar tap likely reaches it)? */
function isTabRoot(id: string): string | null {
  const m = id.match(/^\(tabs\)\/([^/]+)\/index$/);
  return m ? humanize(m[1]) : null;
}

/**
 * Generate the editable Maestro flow scaffold for one chunk. Best-effort nav is
 * emitted for tab roots (tab-bar tap); everything else gets a clearly marked
 * `# TODO` so you fill the taps that reach it. Every screen gets a real
 * `takeScreenshot` with the exact filename the PDF pipeline reads.
 */
export function generateChunkFlow(chunk: Chunk, appId: string, capturesDir: string): string {
  const lines: string[] = [];
  lines.push(`# Maestro flow — ${chunk.title} (${chunk.nodes.length} screens)`);
  lines.push(`# Generated by doc-mcp plan_capture. EDIT the # TODO navigation, then run_flow.`);
  lines.push(`# Auth (if any) runs automatically from .docmcp/skills/auth-flow.yaml before this.`);
  lines.push(`appId: ${appId}`);
  lines.push(`---`);
  lines.push(`- launchApp`);
  lines.push(``);

  for (const node of chunk.nodes) {
    const tab = isTabRoot(node.id);
    lines.push(`# ---- ${node.title}  (${node.route ?? "—"}) ----`);
    if (tab) {
      lines.push(`- tapOn:`);
      lines.push(`    text: ${JSON.stringify(tab)}   # tab bar — verify label`);
    } else {
      lines.push(`# TODO: tap the control(s) that open "${node.title}" from the previous screen.`);
      lines.push(`# e.g.  - tapOn: { text: ${JSON.stringify(humanize(node.id.split("/").pop() ?? node.title))} }`);
    }
    lines.push(`- takeScreenshot: ${screenshotBase(capturesDir, node.id, "default")}`);
    // Non-default states (loading/error/empty…) usually need their own steps.
    for (const st of node.states.filter((s) => s !== "default")) {
      lines.push(`# TODO (optional): reach "${st}" state, then screenshot:`);
      lines.push(`# - takeScreenshot: ${screenshotBase(capturesDir, node.id, st)}`);
    }
    lines.push(``);
  }
  return lines.join("\n");
}
